#!/usr/bin/env bash

readonly CHECKMAN_REPO=$(dirname "${BASH_SOURCE[0]}")/..

function local_changes_exist() {
  git fetch origin
  git status -uno | grep behind &>/dev/null
}

function update_local_repo() {
  echo "Updating local configuration"
  git pull
}

function restart_checkman() {
  pkill -f Checkman
  open /Applications/Checkman.app
}

function main() {
  pushd ${CHECKMAN_REPO} > /dev/null
    if local_changes_exist; then
      update_local_repo
      restart_checkman
    fi
  popd > /dev/null
}

main
